language: python
python:
  - '3.8'

# safelist
branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - sleep 5

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=project8.settings.travis

script:
  - ./manage.py test