language: python
python:
  - '3.8'

addons:
  chrome: stable
  firefox: latest

install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz /home/travis/geckodriver-v0.29.1-linux64.tar.gz
  - gzip -dk ~/geckodriver-v0.29.1-linux64.tar.gz
  - tar -xzf ~/geckodriver-v0.29.1-linux64.tar ~/
  - rm ~/geckodriver-v0.29.1-linux64.tar.gz
  - rm ~/geckodriver-v0.29.1-linux64.tar
  - sudo mv -f ~/geckodriver /usr/local/share
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
# safelist
branches:
  only:
    - main

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=project8.settings.travis

script:
  - ./manage.py test