language: python
python:
    - '3.8'

before_script:
    - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="project8.settings.travis"

services:
    - postgresql

script:
    - ./manage.py test